services:
  frontend:
    build:
      context: ./quiz-frontend
      dockerfile: Dockerfile
    ports:
      - "3001:80"
    depends_on:
      - backend

  backend:
    build:
      context: ./quiz-backend
      dockerfile: Dockerfile
    env_file:
      - ./quiz-backend/.env
    ports:
      - "3000:80"
